In [1]:
#Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore SettingWithCopyWarning
import warnings
warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)

In [2]:
#Reading in our data
superstoreData = pd.read_excel("C://Users//Faith//Downloads//Sample+-+Superstore.xlsx")
superstoreData.head()

C:\Users\Faith\anaconda3\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,EmployeeID
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,5
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,1
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,9
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,6

Transform categorical variables into dummies using the function **get_dummies()** (20 pts)
    * Focus on City, State, Region, EmployeeID, Segment, Category, Sub-Category, and Ship Mode.
    * The transformation of each categorical variable is worth *2.5 pts*

In [3]:
# Specify the categorical columns you want to transform
categorical_columns = ['City', 'State', 'Region', 'EmployeeID', 'Segment', 'Category', 'Sub-Category', 'Ship Mode']

# Create an empty DataFrame to store the dummy variables
dummy_df = pd.DataFrame()

# Apply get_dummies() to each categorical column and concatenate the dummy variables
for column in categorical_columns:
    # Create dummy variables for the current column
    dummies = pd.get_dummies(superstoreData[column], prefix=column, drop_first=True)
    
    # Concatenate the dummy variables to the empty DataFrame
    dummy_df = pd.concat([dummy_df, dummies], axis=1)

# Concatenate the original DataFrame 'superstoreData' with the dummy variables 'dummy_df'
superstoreData = pd.concat([superstoreData, dummy_df], axis=1)

# Display the first few rows of the updated DataFrame to check the added columns
print(superstoreData.head())

# Alternatively, you can display the list of columns in the DataFrame
print(superstoreData.columns)

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156 2017-11-08 2017-11-11    Second Class    CG-12520
1       2  CA-2017-152156 2017-11-08 2017-11-11    Second Class    CG-12520
2       3  CA-2017-138688 2017-06-12 2017-06-16    Second Class    DV-13045
3       4  US-2016-108966 2016-10-11 2016-10-18  Standard Class    SO-20335
4       5  US-2016-108966 2016-10-11 2016-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Sub-Category_Labels  Sub-Category_Machines Sub-Category_Paper  \
0                   0                      0                  0
1                   0                      0                  0
2                   1                      0                  0
3                   0                      0                  0
4                   0                      0                  0

  Sub-Category_Phones Sub-Category_Storage Sub-Category_Supplies  \
0                   0                    0                     0
1                   0                    0                     0
2                   0                    0                     0
3                   0                    0                     0
4                   0                    1                     0

  Sub-Category_Tables  Ship Mode_Same Day  Ship Mode_Second Class  \
0                   0                   0                       1
1                   0                   0                       1
2                   0                   0                       1
3                   1                   0                       0
4                   0                   0                       0

   Ship Mode_Standard Class
0                         0
1                         0
2                         0
3                         1
4                         1

[5 rows x 634 columns]
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City',
       ...
       'Sub-Category_Labels', 'Sub-Category_Machines', 'Sub-Category_Paper',
       'Sub-Category_Phones', 'Sub-Category_Storage', 'Sub-Category_Supplies',
       'Sub-Category_Tables', 'Ship Mode_Same Day', 'Ship Mode_Second Class',
       'Ship Mode_Standard Class'],
      dtype='object', length=634)

In [4]:
superstoreData.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0,0,0,0,0,0,0,0,1,0
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0,0,0,0,0,0,0,0,1,0
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,1,0,0,0,0,0,0,0,1,0
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0,0,0,0,0,0,1,0,0,1
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0,0,0,0,1,0,0,0,0,1

In [5]:
superstoreData.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City',
       ...
       'Sub-Category_Labels', 'Sub-Category_Machines', 'Sub-Category_Paper',
       'Sub-Category_Phones', 'Sub-Category_Storage', 'Sub-Category_Supplies',
       'Sub-Category_Tables', 'Ship Mode_Same Day', 'Ship Mode_Second Class',
       'Ship Mode_Standard Class'],
      dtype='object', length=634)

In [6]:
dummy_df.head()

,City_Abilene,City_Akron,City_Albuquerque,City_Alexandria,City_Allen,City_Allentown,City_Altoona,City_Amarillo,City_Anaheim,City_Andover,...,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

Create a column called "Price" by dividing the column "Sales" with the column "Quantity" (2.5 pts)
    * "Price" represents the average price of the transaction.

In [7]:
superstoreData['Price'] = superstoreData['Sales'] / superstoreData['Quantity']

In [8]:
superstoreData.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City',
       ...
       'Sub-Category_Machines', 'Sub-Category_Paper', 'Sub-Category_Phones',
       'Sub-Category_Storage', 'Sub-Category_Supplies', 'Sub-Category_Tables',
       'Ship Mode_Same Day', 'Ship Mode_Second Class',
       'Ship Mode_Standard Class', 'Price'],
      dtype='object', length=635)

* Create a column called "Shipping Time" representing the number of days between the Order Date and the Ship Date (2.5 pts)
    * The difference between two *datetime64* type variables returns a *timedelta* type variable
    * You can use **dt.days** to convert a *timedelta* to the number of days. Also, you can use Google search to see how to convert a *timedelta* to an *int*. Here is an example https://www.kite.com/python/answers/how-to-convert-a-timedelta-column-in-a-pandas-dataframe-to-a-days-column-in-python

In [9]:
# Convert "Order Date" and "Ship Date" to datetime if not already
superstoreData['Order Date'] = pd.to_datetime(superstoreData['Order Date'])
superstoreData['Ship Date'] = pd.to_datetime(superstoreData['Ship Date'])

# Create the "Shipping Time" column
superstoreData['Shipping Time'] = (superstoreData['Ship Date'] - superstoreData['Order Date']).dt.days

In [10]:
# Se the data in the "Shipping Time" column
shipping_time_data = superstoreData['Shipping Time']

# Display the data in the "Shipping Time" column
print(shipping_time_data)

0       3
1       3
2       4
3       7
4       7
       ..
9989    2
9990    5
9991    5
9992    5
9993    5
Name: Shipping Time, Length: 9994, dtype: int64

* Using **patsy** and **statsmodels**, fit four models that predict *Sales* (25 pts)
    * For each model, choose a different combination of predictors. You can include categorical variables (e.g., State, Region, etc.), and/or numerical variables (e.g., Shipping time, Price, etc.)
    * Each model should have at least 3 predictors
    * Each model is worth *5 pts*
    * Select the best model based on the R-Squared coefficient (5 pts)
        * The best model is the one that has the highest R-Squared coefficient

In [11]:
import patsy
import statsmodels.api as sm

# Model 1: Predictors - 'Shipping Time', 'Price', 'Category'
formula1 = 'Sales ~ Q("Shipping Time") + Price + Category'
y1, X1 = patsy.dmatrices(formula1, data=superstoreData, return_type='dataframe')
model1 = sm.OLS(y1, X1).fit()

# Model 2: Predictors - 'Region', 'Quantity', 'Shipping Time'
formula2 = 'Sales ~ Region + Quantity + Q("Shipping Time")'
y2, X2 = patsy.dmatrices(formula2, data=superstoreData, return_type='dataframe')
model2 = sm.OLS(y2, X2).fit()

# Model 3: Predictors - 'State', 'Category', 'Price'
formula3 = 'Sales ~ State + Category + Price'
y3, X3 = patsy.dmatrices(formula3, data=superstoreData, return_type='dataframe')
model3 = sm.OLS(y3, X3).fit()

# Model 4: Predictors 'Segment', 'Shipping Time', 'Quantity'
formula4 = 'Sales ~ Segment + Q("Shipping Time") + Quantity'
y4, X4 = patsy.dmatrices(formula4, data=superstoreData, return_type='dataframe')
model4 = sm.OLS(y4, X4).fit()

# Compare R-squared values to select the best model
r_squared_values = [model1.rsquared, model2.rsquared, model3.rsquared, model4.rsquared]
best_model_index = r_squared_values.index(max(r_squared_values))

# Display the R-squared values and the best model
print("R-squared values:", r_squared_values)
print("Best model:", best_model_index + 1)  # Adding 1 to match the model numbering

# Printing our models
print("\nModel 1 Summary:\n", model1.summary())
print("\nModel 2 Summary:\n", model2.summary())
print("\nModel 3 Summary:\n", model3.summary())
print("\nModel 4 Summary:\n", model4.summary())

R-squared values: [0.791050196052009, 0.04070896289220316, 0.7916350486924056, 0.04052768731999745]
Best model: 3

Model 1 Summary:
                             OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.791
Model:                            OLS   Adj. R-squared:                  0.791
Method:                 Least Squares   F-statistic:                     9454.
Date:                Sat, 25 Nov 2023   Prob (F-statistic):               0.00
Time:                        21:44:03   Log-Likelihood:                -70668.
No. Observations:                9994   AIC:                         1.413e+05
Df Residuals:                    9989   BIC:                         1.414e+05
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -9.3165      9.104     -1.023      0.306     -27.162       8.529
Category[T.Office Supplies]    -2.7209      7.296     -0.373      0.709     -17.023      11.581
Category[T.Technology]        -11.8064      9.089     -1.299      0.194     -29.623       6.010
Q("Shipping Time")              1.6362      1.631      1.003      0.316      -1.562       4.834
Price                           3.8825      0.021    188.159      0.000       3.842       3.923
==============================================================================
Omnibus:                    10336.127   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          8343918.218
Skew:                           4.244   Prob(JB):                         0.00
Kurtosis:                     144.299   Cond. No.                         670.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Model 2 Summary:
                             OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     84.77
Date:                Sat, 25 Nov 2023   Prob (F-statistic):           1.59e-87
Time:                        21:44:03   Log-Likelihood:                -78283.
No. Observations:                9994   AIC:                         1.566e+05
Df Residuals:                    9988   BIC:                         1.566e+05
Df Model:                           5
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             18.2287     21.544      0.846      0.398     -24.001      60.459
Region[T.East]        24.8968     17.078      1.458      0.145      -8.580      58.374
Region[T.South]       22.6672     19.768      1.147      0.252     -16.081      61.415
Region[T.West]         7.4253     16.646      0.446      0.656     -25.205      40.055
Quantity              56.3336      2.746     20.515      0.000      50.951      61.716
Q("Shipping Time")    -3.7893      3.497     -1.083      0.279     -10.645       3.066
==============================================================================
Omnibus:                    18267.438   Durbin-Watson:                   1.978
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         43779425.937
Skew:                          13.310   Prob(JB):                         0.00
Kurtosis:                     326.149   Cond. No.                         28.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Model 3 Summary:
                             OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.792
Model:                            OLS   Adj. R-squared:                  0.791
Method:                 Least Squares   F-statistic:                     740.6
Date:                Sat, 25 Nov 2023   Prob (F-statistic):               0.00
Time:                        21:44:03   Log-Likelihood:                -70654.
No. Observations:                9994   AIC:                         1.414e+05
Df Residuals:                    9942   BIC:                         1.418e+05
Df Model:                          51
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        33.4404     37.030      0.903      0.367     -39.145     106.026
State[T.Arizona]                -39.5021     41.199     -0.959      0.338    -120.260      41.256
State[T.Arkansas]               -58.4054     51.862     -1.126      0.260    -160.065      43.255
State[T.California]             -37.4141     37.075     -1.009      0.313    -110.088      35.260
State[T.Colorado]               -54.4975     42.207     -1.291      0.197    -137.231      28.236
State[T.Connecticut]            -56.9411     48.233     -1.181      0.238    -151.488      37.606
State[T.Delaware]               -67.7857     46.702     -1.451      0.147    -159.332      23.760
State[T.District of Columbia]    -1.8253     97.314     -0.019      0.985    -192.581     188.930
State[T.Florida]                -18.9442     39.323     -0.482      0.630     -96.026      58.137
State[T.Georgia]                -37.1335     42.140     -0.881      0.378    -119.737      45.470
State[T.Idaho]                  -93.2312     72.167     -1.292      0.196    -234.693      48.231
State[T.Illinois]               -45.3489     38.725     -1.171      0.242    -121.258      30.561
State[T.Indiana]                -11.5984     43.358     -0.268      0.789     -96.588      73.391
State[T.Iowa]                   -13.7863     63.612     -0.217      0.828    -138.478     110.906
State[T.Kansas]                 -90.7597     68.731     -1.320      0.187    -225.487      43.968
State[T.Kentucky]               -34.9501     43.808     -0.798      0.425    -120.822      50.922
State[T.Louisiana]              -77.8093     57.194     -1.360      0.174    -189.921      34.302
State[T.Maine]                  -40.2010    107.259     -0.375      0.708    -250.450     170.048
State[T.Maryland]               -67.6628     45.925     -1.473      0.141    -157.685      22.360
State[T.Massachusetts]          -62.4478     44.009     -1.419      0.156    -148.714      23.818
State[T.Michigan]               -51.4504     40.655     -1.266      0.206    -131.143      28.242
State[T.Minnesota]              -56.2078     47.421     -1.185      0.236    -149.162      36.746
State[T.Mississippi]             -7.0776     53.562     -0.132      0.895    -112.070      97.915
State[T.Missouri]               -30.0643     50.661     -0.593      0.553    -129.370      69.241
State[T.Montana]                -31.9515     82.207     -0.389      0.698    -193.094     129.191
State[T.Nebraska]               -51.3916     58.948     -0.872      0.383    -166.942      64.159
State[T.Nevada]                 -12.9952     58.485     -0.222      0.824    -127.637     101.646
State[T.New Hampshire]            6.1906     65.931      0.094      0.925    -123.047     135.428
State[T.New Jersey]             -24.8306     44.268     -0.561      0.575    -111.605      61.944
State[T.New Mexico]             -27.6826     59.441     -0.466      0.641    -144.199      88.834
State[T.New York]               -41.8564     37.495     -1.116      0.264    -115.354      31.641
State[T.North Carolina]         -34.5993     40.749     -0.849      0.396    -114.475      45.277
State[T.North Dakota]           -31.9152    113.847     -0.280      0.779    -255.079     191.248
State[T.Ohio]                   -50.1374     38.825     -1.291      0.197    -126.243      25.968
State[T.Oklahoma]               -14.4435     50.659     -0.285      0.776    -113.745      84.859
State[T.Oregon]                 -46.0426     44.611     -1.032      0.302    -133.490      41.405
State[T.Pennsylvania]           -26.1568     38.374     -0.682      0.495    -101.377      49.063
State[T.Rhode Island]             9.0201     52.793      0.171      0.864     -94.466     112.506
State[T.South Carolina]         -10.6597     57.195     -0.186      0.852    -122.774     101.455
State[T.South Dakota]           -86.5613     90.075     -0.961      0.337    -263.126      90.003
State[T.Tennessee]              -30.8285     42.182     -0.731      0.465    -113.513      51.856
State[T.Texas]                  -30.1034     37.639     -0.800      0.424    -103.883      43.676
State[T.Utah]                   -37.4369     53.567     -0.699      0.485    -142.438      67.564
State[T.Vermont]                149.7888     93.447      1.603      0.109     -33.387     332.964
State[T.Virginia]               -15.7404     41.196     -0.382      0.702     -96.493      65.013
State[T.Washington]             -37.5224     38.659     -0.971      0.332    -113.302      38.257
State[T.West Virginia]          -20.1512    147.222     -0.137      0.891    -308.737     268.435
State[T.Wisconsin]                6.3655     45.540      0.140      0.889     -82.903      95.634
State[T.Wyoming]                 14.2617    287.674      0.050      0.960    -549.637     578.161
Category[T.Office Supplies]      -2.5783      7.327     -0.352      0.725     -16.940      11.784
Category[T.Technology]          -11.7763      9.120     -1.291      0.197     -29.654       6.102
Price                             3.8810      0.021    186.871      0.000       3.840       3.922
==============================================================================
Omnibus:                    10355.812   Durbin-Watson:                   2.020
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          8386184.500
Skew:                           4.259   Prob(JB):                         0.00
Kurtosis:                     144.656   Cond. No.                     1.61e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.61e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 4 Summary:
                             OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     105.5
Date:                Sat, 25 Nov 2023   Prob (F-statistic):           3.71e-88
Time:                        21:44:03   Log-Likelihood:                -78284.
No. Observations:                9994   AIC:                         1.566e+05
Df Residuals:                    9989   BIC:                         1.566e+05
Df Model:                           4
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 27.5167     19.059      1.444      0.149      -9.843      64.877
Segment[T.Corporate]       5.6665     13.978      0.405      0.685     -21.733      33.066
Segment[T.Home Office]    15.9300     16.761      0.950      0.342     -16.926      48.786
Q("Shipping Time")        -3.9172      3.496     -1.120      0.263     -10.771       2.936
Quantity                  56.2842      2.746     20.497      0.000      50.902      61.667
==============================================================================
Omnibus:                    18264.986   Durbin-Watson:                   1.979
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         43706764.438
Skew:                          13.307   Prob(JB):                         0.00
Kurtosis:                     325.879   Cond. No.                         20.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Note: The best model based on R-Squared coefficient is the third model that had the following predictors: 'State', 'Category', 'Price'

* Fit a model that predicts *Sales* (5 pts)
    * The model should use standardized variables as predictors. The function that standardizes variables is **standardize()**.
    * The list of predictors is: Discount, Price, and Shipping Time.

In [12]:
from sklearn.preprocessing import StandardScaler

#We standardize the following specified columns from our dataframe:
columns_to_standardize = ['Discount', 'Price', 'Shipping Time']

# Create a StandardScaler instance
scaler = StandardScaler()

# Standardize the specified columns
superstoreData[columns_to_standardize] = scaler.fit_transform(superstoreData[columns_to_standardize])

# Model: Predictors - 'Discount', 'Price', 'Shipping Time'
formula = 'Sales ~ Discount + Price + Q("Shipping Time")'
y, X = patsy.dmatrices(formula, data=superstoreData, return_type='dataframe')
model = sm.OLS(y, X).fit()

# Display the model summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.791
Model:                            OLS   Adj. R-squared:                  0.791
Method:                 Least Squares   F-statistic:                 1.260e+04
Date:                Sat, 25 Nov 2023   Prob (F-statistic):               0.00
Time:                        21:44:03   Log-Likelihood:                -70668.
No. Observations:                9994   AIC:                         1.413e+05
Df Residuals:                    9990   BIC:                         1.414e+05
Df Model:                           3
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            229.8580      2.850     80.639      0.000     224.271     235.445
Discount               0.6146      2.852      0.215      0.829      -4.976       6.205
Price                554.3300      2.852    194.348      0.000     548.739     559.921
Q("Shipping Time")     2.8713      2.851      1.007      0.314      -2.717       8.459
==============================================================================
Omnibus:                    10346.523   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          8362020.568
Skew:                           4.252   Prob(JB):                         0.00
Kurtosis:                     144.452   Cond. No.                         1.04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

**Use the following code to create the training and testing datasets should update the path below**

train = superstoreData[:5000]<br>
test = superstoreData[5000:]
**Use the following code to create the outcome to predict**

train['IsProfitable'] = (train['Profit'] >= 0).astype(int)
test['IsProfitable'] = (test['Profit'] >= 0).astype(int)

* Use the LogisticRegression model of scikit-learn to create a model instance (15 pts)
    * Create a list of predictors. You can include the dummies created earlier in the list of predictors (5 pts)
        * The list of predictors should have at least 5 variables
    * Following the lecture notes, fit the model and calculate the y_predict (5 pts)
    * Following the lecture notes, calculate the y_true and the accuracy percentage (5 pts)

In [13]:
train = superstoreData[:5000]
test = superstoreData[5000:]

In [14]:
# Creating 'IsProfitable' variable for the training set
train['IsProfitable'] = (train['Profit'] >= 0).astype(int)

# Creating 'IsProfitable' variable for the testing set
test['IsProfitable'] = (test['Profit'] >= 0).astype(int)

C:\Users\Faith\AppData\Local\Temp\ipykernel_16148\2742580087.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['IsProfitable'] = (train['Profit'] >= 0).astype(int)
C:\Users\Faith\AppData\Local\Temp\ipykernel_16148\2742580087.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['IsProfitable'] = (test['Profit'] >= 0).astype(int)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# List of predictors
predictors = ['Discount', 'Price', 'Shipping Time', 'Sub-Category_Paper', 'Ship Mode_Standard Class', 'City_Abilene', 'State_Arizona', 'EmployeeID_2','Segment_Corporate','Category_Office Supplies']

# Creating the Logistic Regression model
logreg_model = LogisticRegression()

# Fitting the model to the training data
logreg_model.fit(train[predictors], train['IsProfitable'])

# Calculating y_predict on the testing data
y_predict = logreg_model.predict(test[predictors])

# Calculating y_true (actual outcomes) on the testing data
y_true = test['IsProfitable']

# Calculating accuracy percentage
accuracy_percentage = accuracy_score(y_true, y_predict) * 100

# Displaying the accuracy percentage
print(f"Accuracy Percentage: {accuracy_percentage:.2f}%")

Accuracy Percentage: 93.93%